language: rust

services:
  - docker

rust:
  - stable

install:
  - docker-compose up -d mysql
  - cargo install diesel_cli --no-default-features --features mysql

before_script:
  - diesel migration run

script:
  - cargo build
  - cargo test

after_script:
  - docker-compose stop
  - docker-compose rm -f
