language: rust

services:
  - docker

rust:
  - stable

install:
  - docker-compose up -d postgres
  - cargo install diesel_cli --no-default-features --features postgres

before_script:
  - diesel migration run

script:
  - cargo build
  - cargo test

after_script:
  - docker-compose stop
  - docker-compose rm -f
