version: "3.7"
services:
  api:
    environment:
      - DATABASE_URL=mysql://root:strongPassword123@mysql:3306/api_goat
      - RUST_BACKTRACE=full
    build: .
    ports:
    - "3000:3000"
    depends_on:
      - mysql
    expose:
      - "3000"
    entrypoint: ./docker-compose-entrypoint.sh
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=strongPassword123
      - MYSQL_DATABASE=api_goat
    ports:
      - "3306:3306"
    expose:
      - "3306"
