version: "3.7"
services:
  api:
    environment:
      - DATABASE_URL=postgres://root:strongPassword123@postgres:5432/api_goat
      - RUST_BACKTRACE=full
    build: .
    ports:
    - "3000:3000"
    depends_on:
      - postgres
    expose:
      - "3000"
    entrypoint: ./docker-compose-entrypoint.sh
  postgres:
    image: library/postgres:12.4
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=strongPassword123
      - POSTGRES_DB=api_goat
    ports:
      - "5432:5432"
    expose:
      - "5432"
